// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzxfukthxeoycgopstmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6eGZ1a3RoeGVveWNnb3BzdG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODc5OTQsImV4cCI6MjA2MjA2Mzk5NH0.Mob2_GzbuK1bzVEuoKyq9n3PJqma6sTGD9nqbz2mgbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);